- id: fp2_simulate_presence
  alias: FP2 Simulate Presence (Toggle every 30s)
  description: Автоматически переключает fp2_presence для симуляции движения
  trigger:
    - platform: time_pattern
      seconds: "/30"
  condition: []
  action:
    - service: input_boolean.toggle
      target:
        entity_id: input_boolean.fp2_presence
  mode: single
